/**
 * ROBrowser Configuration - bad.ro.turoran.com
 * data.grf + bad.grf layered over translation/rdata for sprites.
 */
window.ROConfigLocal = {
type: "FRAME",
application: "ONLINE",
development: true,
renewal: true,
remoteClient: "https://bad.ro.turoran.com/client/",
servers: [
{
display: "TuroranRO (bad sprites)",
desc: "Turoran server with data.grf + bad.grf on top",
address: "192.168.11.110",
port: 6900,
version: 25,
langtype: 12,
packetver: 20190530,
renewal: true,
worldMapSettings: { episode: 13.2 },
packetKeys: false,
socketProxy: "wss://bad.ro.turoran.com/ws/",
adminList: [2000000]
}
],
packetDump: false,
skipServerList: true,
skipIntro: true,
aura: {},
autoLogin: [],
BGMFileExtension: ["mp3"],
calculateHash: false,
CameraMaxZoomOut: 5,
charBlockSize: 0,
clientHash: null,
clientVersionMode: "PacketVer",
disableConsole: false,
enableAchievements: true,
enableBank: false,
enableCashShop: false,
enableCheckAttendance: true,
enableDmgSuffix: false,
enableHomunAutoFeed: true,
enableMapName: false,
enableRefineUI: true,
enableSignboards: false,
FirstPersonCamera: false,
grfList: null,
hashFiles: [],
loadLua: true,
extraEquipSlots: 0,
customItemInfo: ["System/itemInfo.fixed.lua"],
onReady: null,
plugins: {},
registrationweb: "https://ro.registration.turoran.com",
saveFiles: false,
ThirdPersonCamera: false,
transitionDuration: 200,
forceUseAddress: false
};
